CREATE TABLE [dbo].[Customers]
(
    [Id] UNIQUEIDENTIFIER NOT NULL
        CONSTRAINT PK_Customers PRIMARY KEY,

    [Name] NVARCHAR(200) NOT NULL,
    [TaxId] NVARCHAR(50) UNIQUE NOT NULL,
    [PhoneNumber] NVARCHAR(50) NOT NULL,
    [EmailAddress] NVARCHAR(320) NOT NULL
);